package org.example.xpaymentadapterapp.api;

import org.example.xpaymentadapterapp.api.generated.model.CreateChargeRequest;
import org.example.xpaymentadapterapp.api.generated.model.ChargeResponse;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.Named;
import org.mapstruct.factory.Mappers;
import org.springframework.stereotype.Component;

import java.time.Instant;
import java.time.format.DateTimeFormatter;
import java.util.Currency;

@Mapper(componentModel = "spring")
public interface ChargeMapper {
    ChargeMapper INSTANCE = Mappers.getMapper(ChargeMapper.class);


    @Mapping(target = "id", ignore = true) // ID will be generated by the database
    @Mapping(target = "createdAt", expression = "java(java.time.Instant.now())") // Set createdAt to current time
    @Mapping(target = "chargedAt", ignore = true) // chargedAt will be set later
    @Mapping(source = "currency", target = "currency", qualifiedByName = "stringToCurrency")
    @Mapping(target = "status", expression = "java(org.example.xpaymentadapterapp.api.generated.model.Charge.Status.PROCESSING)")
    @Mapping(source = "order", target = "orderId")
    Charge toEntity(CreateChargeRequest request);

    @Mapping(source = "createdAt", target = "createdAt", qualifiedByName = "instantToString")
    @Mapping(source = "chargedAt", target = "chargedAt", qualifiedByName = "instantToString")
    @Mapping(source = "currency", target = "currency", qualifiedByName = "currencyToString")
    @Mapping(source = "orderId", target = "order")
    @Mapping(source = "amount", target = "amountReceived")
    ChargeResponse toResponse(Charge charge);

    @Named("instantToString")
    static String instantToString(Instant instant) {
        if (instant == null) return null;
        return DateTimeFormatter.ISO_INSTANT.format(instant);
    }

    @Named("stringToInstant")
    static Instant stringToInstant(String isoString) {
        return Instant.parse(isoString);
    }

    @Named("stringToCurrency")
    static Currency stringToCurrency(String currencyCode) {
        return Currency.getInstance(currencyCode);
    }

    @Named("currencyToString")
    static String currencyToString(Currency currency) {
        return currency.getCurrencyCode();
    }
}
